"""
Django settings for project1 project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4-%ybv=go(4$)spixro-3v4ng&!%l6#6qv65i0lao2t+*ncpg7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'sports',
    'musics',
    'news',
    'SHHData',
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',  # 配置更新缓存
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

CACHES = {
    'default':{
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 600,
        'OPTIONS': {
            'MAX_ENTRIES': 1000   # 缓存最大条目数
        }
    }
}
# 另一种格式：缓存配置
# CACHE_MIDDLEWARE_ALIAS = 'default'  #缓存别名
# CACHE_MIDDLEWARE_SECOND = 600       #默认缓存时间
# #CAHCE_MIDDLEWARE_KEY_PREFIX = '127.0.0.1'  #域名配置，避免多个页面同时使用产生冲突
# CACHE_MIDDLEWARE_ANONYMOUS_ONLY = False  #是否只有匿名的请求会被缓存，True为只有匿名用户缓存

ROOT_URLCONF = 'secondHandHousePlatform.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'secondHandHousePlatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'django_test',
        'USER':'root',
        'PASSWORD':'tyl123',
        'HOST':'localhost',
        'PORT':'3306',
    }
}

MONGODB_DATABASES = {
    "default": {
        "name": "secondHandHouse",
        "host": '127.0.0.1',
        "tz_aware": True  # 设置时区
    },
}

LOG_PATH = os.path.join(BASE_DIR, 'log')
# 如果地址不存在，自动创建文件夹
if not os.path.join(LOG_PATH):
    os.mkdir(LOG_PATH)

# 日志系统配置
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {         # 日志格式
#         'default': {
#             'format': '%(asctime)s [%(levalname)s] %(module)s (%(process)d %(thread)d) %(funcName)s %(message)s'
#         },
#         'simple': {
#             'format': ''%(asctime)s [%(levelname)s] %(message)s'
#         },
#     },
#     'filters': {        # 对于特殊字段的过滤（需要根据实际做修改）
#         'special': {
#             '()': 'project.logging.SpecialFilter',
#             'foo': 'bar',
#         },
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'INFO',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#             'formatters': 'simple'
#         },
#         'file_logger':{
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'formatters': 'default',
#             'filepath': '%s/mlog.log'%LOG_PATH
#         },
#         'mail_admins': {        # 邮件处理器
#             'level': 'ERROR',
#             'filters': ['special'],
#             'class': 'django.utils.log.AdminEmailHandler'
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console','file_logger'],
#             'propagate': True,
#         },
#         'django.request': {
#             'handler': ['mail_admin'],  # 对于每一个请求都发送邮件到管理者
#             'level': 'ERROR',
#             'propagate': False,
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
